const router = require('express').Router()

// const user_router = require('../modules/users/user.route')
const auth_router = require('../modules/auth/auth.routes')
const user_router = require('../modules/users/user.route')
const node_router = require('../modules/nodes/node.route')
const gateway_router = require('../modules/gateways/gateway.route')
const building_router = require('../modules/building/building.route')
const company_router = require('../modules/company/company.route')
const weather_router = require('../modules/weather/weather.routes')
const report_router = require('../modules/reports/report.route')
const alert_router = require('../modules/alertion/alert.route')
const fileRoutes = require('./file.routes')
const assetRoutes = require('../modules/assets/asset.routes')
const admin_router = require('../modules/admin-dashboard/admin.routes')
const manager_router = require('../modules/manager-dashboard/dashboard.routes')
const worker_router = require('../modules/worker-dashboard/dashboard.routes')

router.use('/auth', auth_router)
router.use('/users', user_router)
router.use('/nodes', node_router)
router.use('/gateways', gateway_router)
router.use('/buildings', building_router)
router.use('/companies', company_router)
router.use('/weather', weather_router)
router.use('/reports', report_router)
router.use('/alerts', alert_router)
router.use('/files', fileRoutes)
// new routes of image upload aws s3
router.use('/assets', assetRoutes)
router.use('/admin', admin_router)
router.use('/manager', manager_router)
router.use('/worker', worker_router)
module.exports = router
